# Generated by Django 4.2.3 on 2023-07-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='tag',
            field=models.ManyToManyField(to='task.tag'),
        ),
    ]
